// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NetMetric.CRM.IntegrationHub.Infrastructure.Persistence;

#nullable disable

namespace NetMetric.CRM.IntegrationHub.Infrastructure.Migrations;

[DbContext(typeof(IntegrationHubDbContext))]
[Migration("20260503090000_AddProviderCredentialValidationStatus")]
public partial class AddProviderCredentialValidationStatus : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            IF COL_LENGTH(N'dbo.ProviderCredentials', N'ConfigurationJson') IS NULL
                ALTER TABLE [dbo].[ProviderCredentials] ADD [ConfigurationJson] nvarchar(4000) NULL;

            IF COL_LENGTH(N'dbo.ProviderCredentials', N'Status') IS NULL
                ALTER TABLE [dbo].[ProviderCredentials] ADD [Status] nvarchar(40) NOT NULL CONSTRAINT [DF_ProviderCredentials_Status] DEFAULT N'draft';

            IF COL_LENGTH(N'dbo.ProviderCredentials', N'LastValidationStatus') IS NULL
                ALTER TABLE [dbo].[ProviderCredentials] ADD [LastValidationStatus] nvarchar(40) NULL;

            IF COL_LENGTH(N'dbo.ProviderCredentials', N'LastValidationCode') IS NULL
                ALTER TABLE [dbo].[ProviderCredentials] ADD [LastValidationCode] nvarchar(80) NULL;

            IF COL_LENGTH(N'dbo.ProviderCredentials', N'LastValidationMessage') IS NULL
                ALTER TABLE [dbo].[ProviderCredentials] ADD [LastValidationMessage] nvarchar(500) NULL;

            IF COL_LENGTH(N'dbo.ProviderCredentials', N'LastValidatedAtUtc') IS NULL
                ALTER TABLE [dbo].[ProviderCredentials] ADD [LastValidatedAtUtc] datetime2 NULL;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}

