export type CrmModuleStatus = "active" | "read_only" | "contract_pending" | "coming_soon";

export type CrmModuleGroup =
  | "Core CRM"
  | "Sales"
  | "Service / Support"
  | "Marketing"
  | "Operations"
  | "Intelligence / AI"
  | "Administration";

export type CrmModuleRegistryItem = {
  id: string;
  title: string;
  description: string;
  path: string;
  group: CrmModuleGroup;
  iconKey: string;
  status: CrmModuleStatus;
  backendModuleFolder: string;
  endpointDiscoveryStatus: "source_visible" | "contract_pending" | "coming_soon";
  implementationPhase: string;
};

export const crmModuleRegistry: CrmModuleRegistryItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Read-only CRM overview backed by confirmed entity endpoints.",
    path: "/dashboard",
    group: "Core CRM",
    iconKey: "layout-dashboard",
    status: "read_only",
    backendModuleFolder: "AnalyticsReporting",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Implemented",
  },
  {
    id: "customers",
    title: "Customers",
    description: "Customer records with list, detail, and mutation flows.",
    path: "/customers",
    group: "Core CRM",
    iconKey: "users",
    status: "active",
    backendModuleFolder: "CustomerManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Implemented",
  },
  {
    id: "companies",
    title: "Companies",
    description: "Company records with list, detail, and mutation flows.",
    path: "/companies",
    group: "Core CRM",
    iconKey: "building-2",
    status: "active",
    backendModuleFolder: "CustomerManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Implemented",
  },
  {
    id: "contacts",
    title: "Contacts",
    description: "Contact records with list, detail, and mutation flows.",
    path: "/contacts",
    group: "Core CRM",
    iconKey: "contact",
    status: "active",
    backendModuleFolder: "CustomerManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Implemented",
  },
  {
    id: "customer-intelligence",
    title: "Customer Intelligence",
    description: "360 and relationship intelligence endpoints are source-visible.",
    path: "/customer-intelligence",
    group: "Core CRM",
    iconKey: "sparkles",
    status: "contract_pending",
    backendModuleFolder: "CustomerIntelligence",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 11 candidate",
  },
  {
    id: "lead-management",
    title: "Leads",
    description: "Lead records with list, detail, and mutation flows.",
    path: "/leads",
    group: "Sales",
    iconKey: "user-plus",
    status: "active",
    backendModuleFolder: "LeadManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Implemented",
  },
  {
    id: "deal-management",
    title: "Deals",
    description: "Deal endpoints are visible and pending frontend integration.",
    path: "/deals",
    group: "Sales",
    iconKey: "handshake",
    status: "contract_pending",
    backendModuleFolder: "DealManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 11 candidate",
  },
  {
    id: "opportunity-management",
    title: "Opportunities",
    description: "Opportunity records with list, detail, and mutation flows.",
    path: "/opportunities",
    group: "Sales",
    iconKey: "target",
    status: "active",
    backendModuleFolder: "OpportunityManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Implemented",
  },
  {
    id: "pipeline-management",
    title: "Pipeline",
    description: "Pipeline board supports server-validated stage movement.",
    path: "/pipeline",
    group: "Sales",
    iconKey: "git-branch",
    status: "active",
    backendModuleFolder: "PipelineManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Implemented",
  },
  {
    id: "quote-management",
    title: "Quotes",
    description: "Quote lifecycle and CPQ workspace endpoints are visible.",
    path: "/quotes",
    group: "Sales",
    iconKey: "file-text",
    status: "contract_pending",
    backendModuleFolder: "QuoteManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 12 candidate",
  },
  {
    id: "sales-forecasting",
    title: "Sales Forecasting",
    description: "Forecast summary endpoints exist and need UX planning.",
    path: "/sales-forecasting",
    group: "Sales",
    iconKey: "trending-up",
    status: "contract_pending",
    backendModuleFolder: "SalesForecasting",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 12 candidate",
  },
  {
    id: "product-catalog",
    title: "Product Catalog",
    description: "Catalog products APIs are visible and not wired in crm-web yet.",
    path: "/product-catalog",
    group: "Sales",
    iconKey: "package",
    status: "contract_pending",
    backendModuleFolder: "ProductCatalog",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 12 candidate",
  },
  {
    id: "support-inbox",
    title: "Support Inbox",
    description: "Support inbox endpoints are available and pending integration.",
    path: "/support-inbox",
    group: "Service / Support",
    iconKey: "inbox",
    status: "contract_pending",
    backendModuleFolder: "SupportInboxIntegration",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 13 candidate",
  },
  {
    id: "ticket-management",
    title: "Tickets",
    description: "Ticket lifecycle APIs are source-visible.",
    path: "/tickets",
    group: "Service / Support",
    iconKey: "ticket",
    status: "contract_pending",
    backendModuleFolder: "TicketManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 13 candidate",
  },
  {
    id: "ticket-sla",
    title: "Ticket SLA",
    description: "Ticket SLA policy endpoints are source-visible.",
    path: "/ticket-sla",
    group: "Service / Support",
    iconKey: "alarm-clock",
    status: "contract_pending",
    backendModuleFolder: "TicketSlaManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 13 candidate",
  },
  {
    id: "ticket-workflow",
    title: "Ticket Workflows",
    description: "Ticket workflow automation is pending dedicated route contracts.",
    path: "/ticket-workflows",
    group: "Service / Support",
    iconKey: "shuffle",
    status: "coming_soon",
    backendModuleFolder: "TicketWorkflowManagement",
    endpointDiscoveryStatus: "coming_soon",
    implementationPhase: "After ticket module baseline",
  },
  {
    id: "marketing-automation",
    title: "Marketing Automation",
    description: "Campaign and automation endpoints are visible and pending UX mapping.",
    path: "/marketing",
    group: "Marketing",
    iconKey: "megaphone",
    status: "contract_pending",
    backendModuleFolder: "MarketingAutomation",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 14 candidate",
  },
  {
    id: "omnichannel",
    title: "Omnichannel",
    description: "Conversations and channel sync endpoints are source-visible.",
    path: "/omnichannel",
    group: "Marketing",
    iconKey: "messages-square",
    status: "contract_pending",
    backendModuleFolder: "Omnichannel",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 14 candidate",
  },
  {
    id: "calendar-sync",
    title: "Calendar Sync",
    description: "Calendar connection and sync controls are source-visible.",
    path: "/calendar-sync",
    group: "Operations",
    iconKey: "calendar",
    status: "contract_pending",
    backendModuleFolder: "CalendarSync",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 15 candidate",
  },
  {
    id: "contract-lifecycle",
    title: "Contract Lifecycle",
    description: "Contract lifecycle APIs are visible and pending integration.",
    path: "/contracts",
    group: "Operations",
    iconKey: "file-signature",
    status: "contract_pending",
    backendModuleFolder: "ContractLifecycle",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 15 candidate",
  },
  {
    id: "document-management",
    title: "Documents",
    description: "Document and version endpoints are source-visible.",
    path: "/documents",
    group: "Operations",
    iconKey: "folder-open",
    status: "contract_pending",
    backendModuleFolder: "DocumentManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 15 candidate",
  },
  {
    id: "finance-operations",
    title: "Finance",
    description: "Order and finance operations endpoints are visible.",
    path: "/finance",
    group: "Operations",
    iconKey: "wallet",
    status: "contract_pending",
    backendModuleFolder: "FinanceOperations",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 16 candidate",
  },
  {
    id: "integration-hub",
    title: "Integrations",
    description: "Integration hub and webhook operations are source-visible.",
    path: "/integrations",
    group: "Operations",
    iconKey: "plug",
    status: "contract_pending",
    backendModuleFolder: "IntegrationHub",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 16 candidate",
  },
  {
    id: "knowledge-base",
    title: "Knowledge Base",
    description: "Knowledge articles and categories endpoints are source-visible.",
    path: "/knowledge-base",
    group: "Operations",
    iconKey: "book-open",
    status: "contract_pending",
    backendModuleFolder: "KnowledgeBaseManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 16 candidate",
  },
  {
    id: "work-management",
    title: "Work Management",
    description: "Work management workspace endpoints are source-visible.",
    path: "/work-management",
    group: "Operations",
    iconKey: "list-checks",
    status: "contract_pending",
    backendModuleFolder: "WorkManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 17 candidate",
  },
  {
    id: "workflow-automation",
    title: "Workflows",
    description: "Workflow automation rules and executions endpoints are visible.",
    path: "/workflows",
    group: "Operations",
    iconKey: "workflow",
    status: "contract_pending",
    backendModuleFolder: "WorkflowAutomation",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 17 candidate",
  },
  {
    id: "analytics-reporting",
    title: "Analytics",
    description: "Analytics summary and KPI endpoints are source-visible.",
    path: "/analytics",
    group: "Intelligence / AI",
    iconKey: "bar-chart-3",
    status: "contract_pending",
    backendModuleFolder: "AnalyticsReporting",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 18 candidate",
  },
  {
    id: "artificial-intelligence",
    title: "AI",
    description: "AI provider and workspace endpoints are source-visible.",
    path: "/ai",
    group: "Intelligence / AI",
    iconKey: "bot",
    status: "contract_pending",
    backendModuleFolder: "ArtificialIntelligence",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 18 candidate",
  },
  {
    id: "tag-management",
    title: "Tags",
    description: "Tag management endpoints are visible for future integration.",
    path: "/tags",
    group: "Administration",
    iconKey: "tags",
    status: "contract_pending",
    backendModuleFolder: "TagManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 19 candidate",
  },
  {
    id: "tenant-management",
    title: "Tenants",
    description: "Tenant setup and feature flags endpoints are source-visible.",
    path: "/tenants",
    group: "Administration",
    iconKey: "shield",
    status: "contract_pending",
    backendModuleFolder: "TenantManagement",
    endpointDiscoveryStatus: "source_visible",
    implementationPhase: "Phase 19 candidate",
  },
  {
    id: "tasks",
    title: "Tasks",
    description: "Task workflows are pending explicit WorkManagement contract mapping.",
    path: "/tasks",
    group: "Operations",
    iconKey: "check-square",
    status: "contract_pending",
    backendModuleFolder: "WorkManagement",
    endpointDiscoveryStatus: "contract_pending",
    implementationPhase: "After WorkManagement scope alignment",
  },
  {
    id: "activities",
    title: "Activities",
    description:
      "Activity timeline workflows are pending explicit WorkManagement contract mapping.",
    path: "/activities",
    group: "Operations",
    iconKey: "activity",
    status: "contract_pending",
    backendModuleFolder: "WorkManagement",
    endpointDiscoveryStatus: "contract_pending",
    implementationPhase: "After WorkManagement scope alignment",
  },
  {
    id: "settings",
    title: "Settings",
    description: "Workspace settings shell for future policy and preference configuration.",
    path: "/settings",
    group: "Administration",
    iconKey: "settings",
    status: "coming_soon",
    backendModuleFolder: "TenantManagement",
    endpointDiscoveryStatus: "coming_soon",
    implementationPhase: "After tenant settings contracts",
  },
];

export const crmModuleGroups: CrmModuleGroup[] = [
  "Core CRM",
  "Sales",
  "Service / Support",
  "Marketing",
  "Operations",
  "Intelligence / AI",
  "Administration",
];

export function getCrmModuleByPath(path: string): CrmModuleRegistryItem | undefined {
  return crmModuleRegistry.find((moduleItem) => moduleItem.path === path);
}

export function getCrmModuleById(id: string): CrmModuleRegistryItem | undefined {
  return crmModuleRegistry.find((moduleItem) => moduleItem.id === id);
}

export function getCrmModulesByGroup(group: CrmModuleGroup): CrmModuleRegistryItem[] {
  return crmModuleRegistry.filter((moduleItem) => moduleItem.group === group);
}
