// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetMetric.CRM.SupportInboxIntegration.Infrastructure.Migrations;

/// <inheritdoc />
public partial class InitialCreateSupportInboxIntegrationDbContext6384612267 : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {

    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {

    }
}

