// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetMetric.CRM.ProductCatalog.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreateProductCatalogDbContext9169364252 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}

