// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetMetric.CRM.ProductCatalog.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class StabilizeProductCatalogSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Notes",
                table: "ProductBinding");

            migrationBuilder.DropColumn(
                name: "Notes",
                table: "PriceList");

            migrationBuilder.DropColumn(
                name: "Notes",
                table: "DiscountMatrix");

            migrationBuilder.DropColumn(
                name: "Notes",
                table: "CatalogProduct");

            migrationBuilder.DropColumn(
                name: "Notes",
                table: "CatalogCategory");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Notes",
                table: "ProductBinding",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Notes",
                table: "PriceList",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Notes",
                table: "DiscountMatrix",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Notes",
                table: "CatalogProduct",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Notes",
                table: "CatalogCategory",
                type: "nvarchar(max)",
                nullable: true);
        }
    }
}

