// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NetMetric.CRM.Omnichannel.Infrastructure.Persistence;

#nullable disable

namespace NetMetric.CRM.Omnichannel.Infrastructure.Migrations;

[DbContext(typeof(OmnichannelDbContext))]
[Migration("20260501121000_OmnichannelInboxVerticalSlice")]
public partial class OmnichannelInboxVerticalSlice : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            IF OBJECT_ID(N'[dbo].[OmnichannelAccounts]', N'U') IS NULL
            BEGIN
                CREATE TABLE [dbo].[OmnichannelAccounts](
                    [Id] uniqueidentifier NOT NULL,
                    [TenantId] uniqueidentifier NOT NULL,
                    [CreatedAt] datetime2 NOT NULL,
                    [UpdatedAt] datetime2 NULL,
                    [CreatedBy] nvarchar(max) NULL,
                    [UpdatedBy] nvarchar(max) NULL,
                    [IsDeleted] bit NOT NULL CONSTRAINT [DF_OmnichannelAccounts_IsDeleted] DEFAULT(0),
                    [DeletedAt] datetime2 NULL,
                    [DeletedBy] nvarchar(max) NULL,
                    [RowVersion] varbinary(max) NOT NULL CONSTRAINT [DF_OmnichannelAccounts_RowVersion] DEFAULT(0x),
                    [IsActive] bit NOT NULL CONSTRAINT [DF_OmnichannelAccounts_IsActive] DEFAULT(1),
                    [Name] nvarchar(120) NOT NULL,
                    [ChannelType] int NOT NULL,
                    [ExternalAccountId] nvarchar(200) NOT NULL,
                    [SecretReference] nvarchar(300) NOT NULL,
                    [RoutingKey] nvarchar(120) NOT NULL,
                    [ProviderKey] nvarchar(80) NOT NULL CONSTRAINT [DF_OmnichannelAccounts_ProviderKey] DEFAULT('mock'),
                    CONSTRAINT [PK_OmnichannelAccounts] PRIMARY KEY ([Id])
                );
            END;

            IF OBJECT_ID(N'[dbo].[OmnichannelConversations]', N'U') IS NULL
            BEGIN
                CREATE TABLE [dbo].[OmnichannelConversations](
                    [Id] uniqueidentifier NOT NULL,
                    [TenantId] uniqueidentifier NOT NULL,
                    [CreatedAt] datetime2 NOT NULL,
                    [UpdatedAt] datetime2 NULL,
                    [CreatedBy] nvarchar(max) NULL,
                    [UpdatedBy] nvarchar(max) NULL,
                    [IsDeleted] bit NOT NULL CONSTRAINT [DF_OmnichannelConversations_IsDeleted] DEFAULT(0),
                    [DeletedAt] datetime2 NULL,
                    [DeletedBy] nvarchar(max) NULL,
                    [RowVersion] varbinary(max) NOT NULL CONSTRAINT [DF_OmnichannelConversations_RowVersion] DEFAULT(0x),
                    [IsActive] bit NOT NULL CONSTRAINT [DF_OmnichannelConversations_IsActive] DEFAULT(1),
                    [AccountId] uniqueidentifier NOT NULL,
                    [Subject] nvarchar(180) NOT NULL,
                    [CustomerDisplayName] nvarchar(160) NOT NULL,
                    [ExternalConversationId] nvarchar(200) NOT NULL CONSTRAINT [DF_OmnichannelConversations_ExternalConversationId] DEFAULT(''),
                    [ExternalParticipantId] nvarchar(200) NOT NULL CONSTRAINT [DF_OmnichannelConversations_ExternalParticipantId] DEFAULT(''),
                    [ProviderKey] nvarchar(80) NOT NULL CONSTRAINT [DF_OmnichannelConversations_ProviderKey] DEFAULT('mock'),
                    [LeadId] uniqueidentifier NULL,
                    [Status] int NOT NULL,
                    [LastMessageAtUtc] datetime2 NOT NULL,
                    CONSTRAINT [PK_OmnichannelConversations] PRIMARY KEY ([Id])
                );
            END;

            IF OBJECT_ID(N'[dbo].[OmnichannelMessages]', N'U') IS NULL
            BEGIN
                CREATE TABLE [dbo].[OmnichannelMessages](
                    [Id] uniqueidentifier NOT NULL,
                    [TenantId] uniqueidentifier NOT NULL,
                    [CreatedAt] datetime2 NOT NULL,
                    [UpdatedAt] datetime2 NULL,
                    [CreatedBy] nvarchar(max) NULL,
                    [UpdatedBy] nvarchar(max) NULL,
                    [IsDeleted] bit NOT NULL CONSTRAINT [DF_OmnichannelMessages_IsDeleted] DEFAULT(0),
                    [DeletedAt] datetime2 NULL,
                    [DeletedBy] nvarchar(max) NULL,
                    [RowVersion] varbinary(max) NOT NULL CONSTRAINT [DF_OmnichannelMessages_RowVersion] DEFAULT(0x),
                    [IsActive] bit NOT NULL CONSTRAINT [DF_OmnichannelMessages_IsActive] DEFAULT(1),
                    [ConversationId] uniqueidentifier NOT NULL,
                    [Direction] nvarchar(40) NOT NULL,
                    [Body] nvarchar(4000) NOT NULL,
                    [SentAtUtc] datetime2 NOT NULL,
                    [ExternalMessageId] nvarchar(200) NOT NULL,
                    [SenderDisplayName] nvarchar(160) NOT NULL CONSTRAINT [DF_OmnichannelMessages_SenderDisplayName] DEFAULT('Unknown'),
                    [Status] nvarchar(40) NOT NULL CONSTRAINT [DF_OmnichannelMessages_Status] DEFAULT('sent'),
                    CONSTRAINT [PK_OmnichannelMessages] PRIMARY KEY ([Id])
                );
            END;

            IF COL_LENGTH('dbo.OmnichannelAccounts', 'ProviderKey') IS NULL
                ALTER TABLE [dbo].[OmnichannelAccounts] ADD [ProviderKey] nvarchar(80) NOT NULL CONSTRAINT [DF_OmnichannelAccounts_ProviderKey] DEFAULT('mock');
            IF COL_LENGTH('dbo.OmnichannelAccounts', 'IsActive') IS NULL
                ALTER TABLE [dbo].[OmnichannelAccounts] ADD [IsActive] bit NOT NULL CONSTRAINT [DF_OmnichannelAccounts_IsActive] DEFAULT(1);

            IF COL_LENGTH('dbo.OmnichannelConversations', 'ExternalConversationId') IS NULL
                ALTER TABLE [dbo].[OmnichannelConversations] ADD [ExternalConversationId] nvarchar(200) NOT NULL CONSTRAINT [DF_OmnichannelConversations_ExternalConversationId] DEFAULT('');
            IF COL_LENGTH('dbo.OmnichannelConversations', 'ExternalParticipantId') IS NULL
                ALTER TABLE [dbo].[OmnichannelConversations] ADD [ExternalParticipantId] nvarchar(200) NOT NULL CONSTRAINT [DF_OmnichannelConversations_ExternalParticipantId] DEFAULT('');
            IF COL_LENGTH('dbo.OmnichannelConversations', 'ProviderKey') IS NULL
                ALTER TABLE [dbo].[OmnichannelConversations] ADD [ProviderKey] nvarchar(80) NOT NULL CONSTRAINT [DF_OmnichannelConversations_ProviderKey] DEFAULT('mock');
            IF COL_LENGTH('dbo.OmnichannelConversations', 'LeadId') IS NULL
                ALTER TABLE [dbo].[OmnichannelConversations] ADD [LeadId] uniqueidentifier NULL;

            IF COL_LENGTH('dbo.OmnichannelMessages', 'SenderDisplayName') IS NULL
                ALTER TABLE [dbo].[OmnichannelMessages] ADD [SenderDisplayName] nvarchar(160) NOT NULL CONSTRAINT [DF_OmnichannelMessages_SenderDisplayName] DEFAULT('Unknown');
            IF COL_LENGTH('dbo.OmnichannelMessages', 'Status') IS NULL
                ALTER TABLE [dbo].[OmnichannelMessages] ADD [Status] nvarchar(40) NOT NULL CONSTRAINT [DF_OmnichannelMessages_Status] DEFAULT('sent');
            """);

        migrationBuilder.Sql(
            """
            IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_OmnichannelAccounts_TenantId_ProviderKey_ExternalAccountId' AND [object_id] = OBJECT_ID(N'[dbo].[OmnichannelAccounts]'))
                CREATE UNIQUE INDEX [IX_OmnichannelAccounts_TenantId_ProviderKey_ExternalAccountId] ON [dbo].[OmnichannelAccounts] ([TenantId], [ProviderKey], [ExternalAccountId]) WHERE [IsDeleted] = 0;
            IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_OmnichannelConversations_TenantId_ProviderKey_ExternalConversationId' AND [object_id] = OBJECT_ID(N'[dbo].[OmnichannelConversations]'))
                CREATE UNIQUE INDEX [IX_OmnichannelConversations_TenantId_ProviderKey_ExternalConversationId] ON [dbo].[OmnichannelConversations] ([TenantId], [ProviderKey], [ExternalConversationId]) WHERE [IsDeleted] = 0;
            IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_OmnichannelMessages_TenantId_ExternalMessageId' AND [object_id] = OBJECT_ID(N'[dbo].[OmnichannelMessages]'))
                CREATE UNIQUE INDEX [IX_OmnichannelMessages_TenantId_ExternalMessageId] ON [dbo].[OmnichannelMessages] ([TenantId], [ExternalMessageId]) WHERE [IsDeleted] = 0;
            IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_OmnichannelConversations_TenantId_LastMessageAtUtc' AND [object_id] = OBJECT_ID(N'[dbo].[OmnichannelConversations]'))
                CREATE INDEX [IX_OmnichannelConversations_TenantId_LastMessageAtUtc] ON [dbo].[OmnichannelConversations] ([TenantId], [LastMessageAtUtc]);
            IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_OmnichannelMessages_TenantId_ConversationId_SentAtUtc' AND [object_id] = OBJECT_ID(N'[dbo].[OmnichannelMessages]'))
                CREATE INDEX [IX_OmnichannelMessages_TenantId_ConversationId_SentAtUtc] ON [dbo].[OmnichannelMessages] ([TenantId], [ConversationId], [SentAtUtc]);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}

