// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetMetric.CRM.MarketingAutomation.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MarketingAutomationEngineP0 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "CriteriaJson",
                table: "Segment",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "IsSuppression",
                table: "Segment",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastEvaluatedAtUtc",
                table: "Segment",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "LastEvaluatedCount",
                table: "Segment",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "SegmentType",
                table: "Segment",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<Guid>(
                name: "EntrySegmentId",
                table: "LeadNurturingJourney",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "PausedAtUtc",
                table: "LeadNurturingJourney",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "StartedAtUtc",
                table: "LeadNurturingJourney",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Status",
                table: "LeadNurturingJourney",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "StepDefinitionJson",
                table: "LeadNurturingJourney",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "DeliverabilityStatus",
                table: "EmailCampaign",
                type: "nvarchar(80)",
                maxLength: 80,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "FromEmail",
                table: "EmailCampaign",
                type: "nvarchar(320)",
                maxLength: 320,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "FromName",
                table: "EmailCampaign",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "HtmlBody",
                table: "EmailCampaign",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTime>(
                name: "LastPreviewedAtUtc",
                table: "EmailCampaign",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Subject",
                table: "EmailCampaign",
                type: "nvarchar(300)",
                maxLength: 300,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "TextBody",
                table: "EmailCampaign",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<Guid>(
                name: "CampaignId",
                table: "CampaignMember",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<int>(
                name: "ClickCount",
                table: "CampaignMember",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "ConsentStatus",
                table: "CampaignMember",
                type: "nvarchar(80)",
                maxLength: 80,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<Guid>(
                name: "ContactId",
                table: "CampaignMember",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "EmailAddress",
                table: "CampaignMember",
                type: "nvarchar(320)",
                maxLength: 320,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "EmailHash",
                table: "CampaignMember",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTime>(
                name: "LastSentAtUtc",
                table: "CampaignMember",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "OpenCount",
                table: "CampaignMember",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "SentCount",
                table: "CampaignMember",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "Suppressed",
                table: "CampaignMember",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "ApprovalStatus",
                table: "Campaign",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<Guid>(
                name: "ApprovalWorkflowId",
                table: "Campaign",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "BudgetAmount",
                table: "Campaign",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<DateTime>(
                name: "CanceledAtUtc",
                table: "Campaign",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Channel",
                table: "Campaign",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTime>(
                name: "CompletedAtUtc",
                table: "Campaign",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "EmailTemplateId",
                table: "Campaign",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "ExpectedRevenueAmount",
                table: "Campaign",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "FrequencyCapPerContact",
                table: "Campaign",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "FrequencyCapWindowDays",
                table: "Campaign",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "PausedAtUtc",
                table: "Campaign",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ScheduledAtUtc",
                table: "Campaign",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SegmentId",
                table: "Campaign",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "StartedAtUtc",
                table: "Campaign",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Status",
                table: "Campaign",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "UtmCampaign",
                table: "Campaign",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateTable(
                name: "CampaignAttribution",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CampaignId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    EmailHash = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    TouchType = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                    RevenueAmount = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    CostAmount = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    UtmSource = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: false),
                    UtmMedium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: false),
                    UtmCampaign = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    OccurredAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "varbinary(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CampaignAttribution", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "CampaignRoiProjection",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CampaignId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SentCount = table.Column<int>(type: "int", nullable: false),
                    SuppressedCount = table.Column<int>(type: "int", nullable: false),
                    RevenueAmount = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    CostAmount = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    RoiPercent = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    CalculatedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "varbinary(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CampaignRoiProjection", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "JourneyStepExecution",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    JourneyId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    StepKey = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    EmailHash = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    Status = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    ScheduledAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    NextAttemptAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    AttemptNumber = table.Column<int>(type: "int", nullable: false),
                    MaxAttempts = table.Column<int>(type: "int", nullable: false),
                    IdempotencyKey = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    ErrorMessage = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "varbinary(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_JourneyStepExecution", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "MarketingConsent",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    EmailAddress = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: false),
                    EmailHash = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    Status = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                    Source = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    DoubleOptInRequired = table.Column<bool>(type: "bit", nullable: false),
                    DoubleOptInTokenHash = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    GrantedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RevokedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "varbinary(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MarketingConsent", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "MarketingEmailDelivery",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CampaignId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    JourneyId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    JourneyStepExecutionId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    EmailHash = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    Status = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    IdempotencyKey = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    CorrelationId = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    AttemptNumber = table.Column<int>(type: "int", nullable: false),
                    MaxAttempts = table.Column<int>(type: "int", nullable: false),
                    ScheduledAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    NextAttemptAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SentAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    FailedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    FailureCode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    FailureMessage = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "varbinary(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MarketingEmailDelivery", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SuppressionEntry",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    EmailAddress = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: false),
                    EmailHash = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    Reason = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Source = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    SuppressedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "varbinary(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SuppressionEntry", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Segment_TenantId_SegmentType_IsActive",
                table: "Segment",
                columns: new[] { "TenantId", "SegmentType", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_LeadNurturingJourney_TenantId_Status",
                table: "LeadNurturingJourney",
                columns: new[] { "TenantId", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_CampaignMember_TenantId_CampaignId_EmailHash",
                table: "CampaignMember",
                columns: new[] { "TenantId", "CampaignId", "EmailHash" },
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_Campaign_TenantId_Status_ScheduledAtUtc",
                table: "Campaign",
                columns: new[] { "TenantId", "Status", "ScheduledAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_CampaignAttribution_TenantId_CampaignId_OccurredAtUtc",
                table: "CampaignAttribution",
                columns: new[] { "TenantId", "CampaignId", "OccurredAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_CampaignRoiProjection_TenantId_CampaignId",
                table: "CampaignRoiProjection",
                columns: new[] { "TenantId", "CampaignId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_JourneyStepExecution_TenantId_IdempotencyKey",
                table: "JourneyStepExecution",
                columns: new[] { "TenantId", "IdempotencyKey" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_JourneyStepExecution_TenantId_Status_NextAttemptAtUtc",
                table: "JourneyStepExecution",
                columns: new[] { "TenantId", "Status", "NextAttemptAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_MarketingConsent_TenantId_EmailHash",
                table: "MarketingConsent",
                columns: new[] { "TenantId", "EmailHash" },
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_MarketingEmailDelivery_TenantId_EmailHash_SentAtUtc",
                table: "MarketingEmailDelivery",
                columns: new[] { "TenantId", "EmailHash", "SentAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_MarketingEmailDelivery_TenantId_IdempotencyKey",
                table: "MarketingEmailDelivery",
                columns: new[] { "TenantId", "IdempotencyKey" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MarketingEmailDelivery_TenantId_Status_NextAttemptAtUtc",
                table: "MarketingEmailDelivery",
                columns: new[] { "TenantId", "Status", "NextAttemptAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_SuppressionEntry_TenantId_EmailHash",
                table: "SuppressionEntry",
                columns: new[] { "TenantId", "EmailHash" },
                unique: true,
                filter: "[IsDeleted] = 0");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CampaignAttribution");

            migrationBuilder.DropTable(
                name: "CampaignRoiProjection");

            migrationBuilder.DropTable(
                name: "JourneyStepExecution");

            migrationBuilder.DropTable(
                name: "MarketingConsent");

            migrationBuilder.DropTable(
                name: "MarketingEmailDelivery");

            migrationBuilder.DropTable(
                name: "SuppressionEntry");

            migrationBuilder.DropIndex(
                name: "IX_Segment_TenantId_SegmentType_IsActive",
                table: "Segment");

            migrationBuilder.DropIndex(
                name: "IX_LeadNurturingJourney_TenantId_Status",
                table: "LeadNurturingJourney");

            migrationBuilder.DropIndex(
                name: "IX_CampaignMember_TenantId_CampaignId_EmailHash",
                table: "CampaignMember");

            migrationBuilder.DropIndex(
                name: "IX_Campaign_TenantId_Status_ScheduledAtUtc",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "CriteriaJson",
                table: "Segment");

            migrationBuilder.DropColumn(
                name: "IsSuppression",
                table: "Segment");

            migrationBuilder.DropColumn(
                name: "LastEvaluatedAtUtc",
                table: "Segment");

            migrationBuilder.DropColumn(
                name: "LastEvaluatedCount",
                table: "Segment");

            migrationBuilder.DropColumn(
                name: "SegmentType",
                table: "Segment");

            migrationBuilder.DropColumn(
                name: "EntrySegmentId",
                table: "LeadNurturingJourney");

            migrationBuilder.DropColumn(
                name: "PausedAtUtc",
                table: "LeadNurturingJourney");

            migrationBuilder.DropColumn(
                name: "StartedAtUtc",
                table: "LeadNurturingJourney");

            migrationBuilder.DropColumn(
                name: "Status",
                table: "LeadNurturingJourney");

            migrationBuilder.DropColumn(
                name: "StepDefinitionJson",
                table: "LeadNurturingJourney");

            migrationBuilder.DropColumn(
                name: "DeliverabilityStatus",
                table: "EmailCampaign");

            migrationBuilder.DropColumn(
                name: "FromEmail",
                table: "EmailCampaign");

            migrationBuilder.DropColumn(
                name: "FromName",
                table: "EmailCampaign");

            migrationBuilder.DropColumn(
                name: "HtmlBody",
                table: "EmailCampaign");

            migrationBuilder.DropColumn(
                name: "LastPreviewedAtUtc",
                table: "EmailCampaign");

            migrationBuilder.DropColumn(
                name: "Subject",
                table: "EmailCampaign");

            migrationBuilder.DropColumn(
                name: "TextBody",
                table: "EmailCampaign");

            migrationBuilder.DropColumn(
                name: "CampaignId",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "ClickCount",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "ConsentStatus",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "ContactId",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "EmailAddress",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "EmailHash",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "LastSentAtUtc",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "OpenCount",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "SentCount",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "Suppressed",
                table: "CampaignMember");

            migrationBuilder.DropColumn(
                name: "ApprovalStatus",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "ApprovalWorkflowId",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "BudgetAmount",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "CanceledAtUtc",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "Channel",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "CompletedAtUtc",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "EmailTemplateId",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "ExpectedRevenueAmount",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "FrequencyCapPerContact",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "FrequencyCapWindowDays",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "PausedAtUtc",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "ScheduledAtUtc",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "SegmentId",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "StartedAtUtc",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "Status",
                table: "Campaign");

            migrationBuilder.DropColumn(
                name: "UtmCampaign",
                table: "Campaign");

        }
    }
}

