// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetMetric.CRM.LeadManagement.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddLeadScoringAndAttributionSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ForecastCategory",
                table: "Opportunities",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<Guid>(
                name: "PipelineId",
                table: "Opportunities",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "PipelineStageId",
                table: "Opportunities",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "EngagementScoreDelta",
                table: "LeadScores",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "FitScoreDelta",
                table: "LeadScores",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<string>(
                name: "RuleId",
                table: "LeadScores",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "AiScore",
                table: "Leads",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "CaptureFormId",
                table: "Leads",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "CurrentNurtureJourneyId",
                table: "Leads",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DisqualificationNote",
                table: "Leads",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "DisqualificationReasonId",
                table: "Leads",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "EngagementScore",
                table: "Leads",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<DateTime>(
                name: "FirstContactTime",
                table: "Leads",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "FitScore",
                table: "Leads",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "Grade",
                table: "Leads",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "IsAiScored",
                table: "Leads",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsSpam",
                table: "Leads",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<Guid>(
                name: "MergedIntoLeadId",
                table: "Leads",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "NurtureState",
                table: "Leads",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "QualificationData",
                table: "Leads",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "QualificationFramework",
                table: "Leads",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "ReferrerUrl",
                table: "Leads",
                type: "nvarchar(1024)",
                maxLength: 1024,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "SlaBreached",
                table: "Leads",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "SlaTargetTime",
                table: "Leads",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "SourceRoi",
                table: "Leads",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "TimeToContactMinutes",
                table: "Leads",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "TotalScore",
                table: "Leads",
                type: "decimal(18,2)",
                precision: 18,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<string>(
                name: "UtmCampaign",
                table: "Leads",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UtmContent",
                table: "Leads",
                type: "nvarchar(256)",
                maxLength: 256,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UtmMedium",
                table: "Leads",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UtmSource",
                table: "Leads",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UtmTerm",
                table: "Leads",
                type: "nvarchar(256)",
                maxLength: 256,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "LeadOwnershipHistories",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    LeadId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    PreviousOwnerId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    NewOwnerId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AssignmentReason = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    AssignmentRuleId = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    AssignedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    AssignedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LeadOwnershipHistories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_LeadOwnershipHistories_Leads_LeadId",
                        column: x => x.LeadId,
                        principalTable: "Leads",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Leads_DisqualificationReasonId",
                table: "Leads",
                column: "DisqualificationReasonId");

            migrationBuilder.CreateIndex(
                name: "IX_Leads_MergedIntoLeadId",
                table: "Leads",
                column: "MergedIntoLeadId");

            migrationBuilder.CreateIndex(
                name: "IX_LeadOwnershipHistories_LeadId",
                table: "LeadOwnershipHistories",
                column: "LeadId");

            migrationBuilder.CreateIndex(
                name: "IX_LeadOwnershipHistories_TenantId_LeadId_AssignedAt",
                table: "LeadOwnershipHistories",
                columns: new[] { "TenantId", "LeadId", "AssignedAt" });

            migrationBuilder.AddForeignKey(
                name: "FK_Leads_Leads_MergedIntoLeadId",
                table: "Leads",
                column: "MergedIntoLeadId",
                principalTable: "Leads",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Leads_LostReason_DisqualificationReasonId",
                table: "Leads",
                column: "DisqualificationReasonId",
                principalTable: "LostReason",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Leads_Leads_MergedIntoLeadId",
                table: "Leads");

            migrationBuilder.DropForeignKey(
                name: "FK_Leads_LostReason_DisqualificationReasonId",
                table: "Leads");

            migrationBuilder.DropTable(
                name: "LeadOwnershipHistories");

            migrationBuilder.DropIndex(
                name: "IX_Leads_DisqualificationReasonId",
                table: "Leads");

            migrationBuilder.DropIndex(
                name: "IX_Leads_MergedIntoLeadId",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "ForecastCategory",
                table: "Opportunities");

            migrationBuilder.DropColumn(
                name: "PipelineId",
                table: "Opportunities");

            migrationBuilder.DropColumn(
                name: "PipelineStageId",
                table: "Opportunities");

            migrationBuilder.DropColumn(
                name: "EngagementScoreDelta",
                table: "LeadScores");

            migrationBuilder.DropColumn(
                name: "FitScoreDelta",
                table: "LeadScores");

            migrationBuilder.DropColumn(
                name: "RuleId",
                table: "LeadScores");

            migrationBuilder.DropColumn(
                name: "AiScore",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "CaptureFormId",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "CurrentNurtureJourneyId",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "DisqualificationNote",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "DisqualificationReasonId",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "EngagementScore",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "FirstContactTime",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "FitScore",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "Grade",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "IsAiScored",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "IsSpam",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "MergedIntoLeadId",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "NurtureState",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "QualificationData",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "QualificationFramework",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "ReferrerUrl",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "SlaBreached",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "SlaTargetTime",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "SourceRoi",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "TimeToContactMinutes",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "TotalScore",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "UtmCampaign",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "UtmContent",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "UtmMedium",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "UtmSource",
                table: "Leads");

            migrationBuilder.DropColumn(
                name: "UtmTerm",
                table: "Leads");
        }
    }
}

